// Generated by the protocol buffer compiler.  DO NOT EDIT!

package org.xottys.serializedemo;

public final class StudentPB {
  private StudentPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StudentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>uint32 age = 2;</code>
     */
    int getAge();

    /**
     * <code>bool isMale = 3;</code>
     */
    boolean getIsMale();

    /**
     * <code>float weight = 4;</code>
     */
    float getWeight();

    /**
     * <code>repeated string favoriteBooks = 5;</code>
     */
    java.util.List<String>
        getFavoriteBooksList();
    /**
     * <code>repeated string favoriteBooks = 5;</code>
     */
    int getFavoriteBooksCount();
    /**
     * <code>repeated string favoriteBooks = 5;</code>
     */
    String getFavoriteBooks(int index);
    /**
     * <code>repeated string favoriteBooks = 5;</code>
     */
    com.google.protobuf.ByteString
        getFavoriteBooksBytes(int index);

    /**
     * <code>repeated string interests = 6;</code>
     */
    java.util.List<String>
        getInterestsList();
    /**
     * <code>repeated string interests = 6;</code>
     */
    int getInterestsCount();
    /**
     * <code>repeated string interests = 6;</code>
     */
    String getInterests(int index);
    /**
     * <code>repeated string interests = 6;</code>
     */
    com.google.protobuf.ByteString
        getInterestsBytes(int index);
  }
  /**
   * Protobuf type {@code Student}
   */
  public  static final class Student extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Student)
      StudentOrBuilder {
    // Use Student.newBuilder() to construct.
    private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Student() {
      name_ = "";
      age_ = 0;
      isMale_ = false;
      weight_ = 0F;
      favoriteBooks_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      interests_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Student(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              age_ = input.readUInt32();
              break;
            }
            case 24: {

              isMale_ = input.readBool();
              break;
            }
            case 37: {

              weight_ = input.readFloat();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                favoriteBooks_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              favoriteBooks_.add(s);
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                interests_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              interests_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          favoriteBooks_ = favoriteBooks_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          interests_ = interests_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return StudentPB.internal_static_Student_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return StudentPB.internal_static_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Student.class, Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>uint32 age = 2;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int ISMALE_FIELD_NUMBER = 3;
    private boolean isMale_;
    /**
     * <code>bool isMale = 3;</code>
     */
    public boolean getIsMale() {
      return isMale_;
    }

    public static final int WEIGHT_FIELD_NUMBER = 4;
    private float weight_;
    /**
     * <code>float weight = 4;</code>
     */
    public float getWeight() {
      return weight_;
    }

    public static final int FAVORITEBOOKS_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList favoriteBooks_;
    /**
     * <code>repeated string favoriteBooks = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getFavoriteBooksList() {
      return favoriteBooks_;
    }
    /**
     * <code>repeated string favoriteBooks = 5;</code>
     */
    public int getFavoriteBooksCount() {
      return favoriteBooks_.size();
    }
    /**
     * <code>repeated string favoriteBooks = 5;</code>
     */
    public String getFavoriteBooks(int index) {
      return favoriteBooks_.get(index);
    }
    /**
     * <code>repeated string favoriteBooks = 5;</code>
     */
    public com.google.protobuf.ByteString
        getFavoriteBooksBytes(int index) {
      return favoriteBooks_.getByteString(index);
    }

    public static final int INTERESTS_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList interests_;
    /**
     * <code>repeated string interests = 6;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getInterestsList() {
      return interests_;
    }
    /**
     * <code>repeated string interests = 6;</code>
     */
    public int getInterestsCount() {
      return interests_.size();
    }
    /**
     * <code>repeated string interests = 6;</code>
     */
    public String getInterests(int index) {
      return interests_.get(index);
    }
    /**
     * <code>repeated string interests = 6;</code>
     */
    public com.google.protobuf.ByteString
        getInterestsBytes(int index) {
      return interests_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (age_ != 0) {
        output.writeUInt32(2, age_);
      }
      if (isMale_ != false) {
        output.writeBool(3, isMale_);
      }
      if (weight_ != 0F) {
        output.writeFloat(4, weight_);
      }
      for (int i = 0; i < favoriteBooks_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, favoriteBooks_.getRaw(i));
      }
      for (int i = 0; i < interests_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, interests_.getRaw(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, age_);
      }
      if (isMale_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isMale_);
      }
      if (weight_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, weight_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < favoriteBooks_.size(); i++) {
          dataSize += computeStringSizeNoTag(favoriteBooks_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getFavoriteBooksList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < interests_.size(); i++) {
          dataSize += computeStringSizeNoTag(interests_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getInterestsList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Student)) {
        return super.equals(obj);
      }
      Student other = (Student) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && (getAge()
          == other.getAge());
      result = result && (getIsMale()
          == other.getIsMale());
      result = result && (
          Float.floatToIntBits(getWeight())
          == Float.floatToIntBits(
              other.getWeight()));
      result = result && getFavoriteBooksList()
          .equals(other.getFavoriteBooksList());
      result = result && getInterestsList()
          .equals(other.getInterestsList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + ISMALE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsMale());
      hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getWeight());
      if (getFavoriteBooksCount() > 0) {
        hash = (37 * hash) + FAVORITEBOOKS_FIELD_NUMBER;
        hash = (53 * hash) + getFavoriteBooksList().hashCode();
      }
      if (getInterestsCount() > 0) {
        hash = (37 * hash) + INTERESTS_FIELD_NUMBER;
        hash = (53 * hash) + getInterestsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Student parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Student parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Student)
        StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return StudentPB.internal_static_Student_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return StudentPB.internal_static_Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Student.class, Builder.class);
      }

      // Construct using org.xottys.serializedemo.StudentPB.Student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        age_ = 0;

        isMale_ = false;

        weight_ = 0F;

        favoriteBooks_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        interests_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return StudentPB.internal_static_Student_descriptor;
      }

      public Student getDefaultInstanceForType() {
        return Student.getDefaultInstance();
      }

      public Student build() {
        Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Student buildPartial() {
        Student result = new Student(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.name_ = name_;
        result.age_ = age_;
        result.isMale_ = isMale_;
        result.weight_ = weight_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          favoriteBooks_ = favoriteBooks_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.favoriteBooks_ = favoriteBooks_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          interests_ = interests_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.interests_ = interests_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Student) {
          return mergeFrom((Student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Student other) {
        if (other == Student.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.getIsMale() != false) {
          setIsMale(other.getIsMale());
        }
        if (other.getWeight() != 0F) {
          setWeight(other.getWeight());
        }
        if (!other.favoriteBooks_.isEmpty()) {
          if (favoriteBooks_.isEmpty()) {
            favoriteBooks_ = other.favoriteBooks_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureFavoriteBooksIsMutable();
            favoriteBooks_.addAll(other.favoriteBooks_);
          }
          onChanged();
        }
        if (!other.interests_.isEmpty()) {
          if (interests_.isEmpty()) {
            interests_ = other.interests_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureInterestsIsMutable();
            interests_.addAll(other.interests_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Student parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Student) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>uint32 age = 2;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>uint32 age = 2;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 age = 2;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private boolean isMale_ ;
      /**
       * <code>bool isMale = 3;</code>
       */
      public boolean getIsMale() {
        return isMale_;
      }
      /**
       * <code>bool isMale = 3;</code>
       */
      public Builder setIsMale(boolean value) {
        
        isMale_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isMale = 3;</code>
       */
      public Builder clearIsMale() {
        
        isMale_ = false;
        onChanged();
        return this;
      }

      private float weight_ ;
      /**
       * <code>float weight = 4;</code>
       */
      public float getWeight() {
        return weight_;
      }
      /**
       * <code>float weight = 4;</code>
       */
      public Builder setWeight(float value) {
        
        weight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float weight = 4;</code>
       */
      public Builder clearWeight() {
        
        weight_ = 0F;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList favoriteBooks_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFavoriteBooksIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          favoriteBooks_ = new com.google.protobuf.LazyStringArrayList(favoriteBooks_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string favoriteBooks = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getFavoriteBooksList() {
        return favoriteBooks_.getUnmodifiableView();
      }
      /**
       * <code>repeated string favoriteBooks = 5;</code>
       */
      public int getFavoriteBooksCount() {
        return favoriteBooks_.size();
      }
      /**
       * <code>repeated string favoriteBooks = 5;</code>
       */
      public String getFavoriteBooks(int index) {
        return favoriteBooks_.get(index);
      }
      /**
       * <code>repeated string favoriteBooks = 5;</code>
       */
      public com.google.protobuf.ByteString
          getFavoriteBooksBytes(int index) {
        return favoriteBooks_.getByteString(index);
      }
      /**
       * <code>repeated string favoriteBooks = 5;</code>
       */
      public Builder setFavoriteBooks(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFavoriteBooksIsMutable();
        favoriteBooks_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string favoriteBooks = 5;</code>
       */
      public Builder addFavoriteBooks(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFavoriteBooksIsMutable();
        favoriteBooks_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string favoriteBooks = 5;</code>
       */
      public Builder addAllFavoriteBooks(
          Iterable<String> values) {
        ensureFavoriteBooksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, favoriteBooks_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string favoriteBooks = 5;</code>
       */
      public Builder clearFavoriteBooks() {
        favoriteBooks_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string favoriteBooks = 5;</code>
       */
      public Builder addFavoriteBooksBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureFavoriteBooksIsMutable();
        favoriteBooks_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList interests_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureInterestsIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          interests_ = new com.google.protobuf.LazyStringArrayList(interests_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string interests = 6;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getInterestsList() {
        return interests_.getUnmodifiableView();
      }
      /**
       * <code>repeated string interests = 6;</code>
       */
      public int getInterestsCount() {
        return interests_.size();
      }
      /**
       * <code>repeated string interests = 6;</code>
       */
      public String getInterests(int index) {
        return interests_.get(index);
      }
      /**
       * <code>repeated string interests = 6;</code>
       */
      public com.google.protobuf.ByteString
          getInterestsBytes(int index) {
        return interests_.getByteString(index);
      }
      /**
       * <code>repeated string interests = 6;</code>
       */
      public Builder setInterests(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInterestsIsMutable();
        interests_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string interests = 6;</code>
       */
      public Builder addInterests(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInterestsIsMutable();
        interests_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string interests = 6;</code>
       */
      public Builder addAllInterests(
          Iterable<String> values) {
        ensureInterestsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, interests_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string interests = 6;</code>
       */
      public Builder clearInterests() {
        interests_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string interests = 6;</code>
       */
      public Builder addInterestsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureInterestsIsMutable();
        interests_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Student)
    }

    // @@protoc_insertion_point(class_scope:Student)
    private static final Student DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Student();
    }

    public static Student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Student>
        PARSER = new com.google.protobuf.AbstractParser<Student>() {
      public Student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Student(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Student> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Student> getParserForType() {
      return PARSER;
    }

    public Student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Student_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Student_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rstudent.proto\"n\n\007Student\022\014\n\004name\030\001 \001(\t" +
      "\022\013\n\003age\030\002 \001(\r\022\016\n\006isMale\030\003 \001(\010\022\016\n\006weight\030" +
      "\004 \001(\002\022\025\n\rfavoriteBooks\030\005 \003(\t\022\021\n\tinterest" +
      "s\030\006 \003(\tB%\n\030org.xottys.serializedemoB\tStu" +
      "dentPBb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Student_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Student_descriptor,
        new String[] { "Name", "Age", "IsMale", "Weight", "FavoriteBooks", "Interests", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
